# Generated by Django 6.0.3 on 2026-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='average_dispatch',
            field=models.CharField(choices=[('same_day', 'Same Day'), ('1_day', '1 Day'), ('2_day', '2 Day')], default='same_day', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_type',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_p_name',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='dist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='have_gst',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='monthly_order',
            field=models.CharField(blank=True, choices=[('0-100', '0-100'), ('100-500', '100-500'), ('500+', '500+')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='name_as_per_pan',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pan',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pick_add_one',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pick_add_two',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=115, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_land_mark',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pickup_state',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='products_category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('beauty', 'Beauty'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='room_building',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='store_display_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='street_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
